# Product SKU? : (product name, newegg part #)
PRODUCT_INFO = {
    "PulseLabz Guardian Series Gaming Chair - Black/Black": ("9SIAFG16RF1304", "G-BK"),
    "PulseLabz Guardian Series Office Gaming Chair - Black/Black": ("9SIAFG16RF1304", "G-BK"),
    "PulseLabz Guardian Series Gaming Chair - White/Black": ("9SIAFG16RF1303", "G-W"),
    "PulseLabz Guardian Series Gaming Chair - Blue/Black": ("9SIAFG16RF1302", "G-B"),
    "PulseLabz Guardian Series Gaming Chair - Red/Black": ("9SIAFG16RF1269", "G-R"),
    "PulseLabz Enforcer Series Gaming Chair - Black/Black": ("9SIAFG16RE9293", "E-BK"),
    "PulseLabz Enforcer Series Office Gaming Chair - Black/Black": ("9SIAFG16RE9293", "E-BK"),
    "PulseLabz Enforcer Series Gaming Chair - White/Black": ("9SIAFG16RE9292", "E-W"),
    "PulseLabz Enforcer Series Gaming Chair - Blue/Black": ("9SIAFG16RE9291", "E-B"),
    "PulseLabz Enforcer Series Gaming Chair - Red/Black": ("9SIAFG16RE9105", "E-R"),
    "PulseLabz Challenger Series Gaming Chair - Black/Black": ("9SIAFG16RE9054", "C-BK"),
    "PulseLabz Challenger Series Office Gaming Chair - Black/Black": ("9SIAFG16RE9054", "C-BK"),
    "PulseLabz Challenger Series Gaming Chair - White/Black": ("9SIAFG16RE8116", "C-W"),
    "PulseLabz Challenger Series Gaming Chair - Blue/Black": ("9SIAFG16RE8111", "C-B"),
    "PulseLabz Challenger Series Gaming Chair - Red/Black": ("9SIAFG16R80209", "C-R"),
    "PulseLabz Challenger Series Gaming Chair (W-trim) - White/Black": ('', "C-W"),
    "PulseLabz Challenger Series Gaming Chair - Green/Black": ('', "C-G"),
    "PulseLabz Challenger Series Gaming Chair - Orange/Black": ('', "C-O"),
    "Pulselabz Weapon Series Mousepad": ("9SIAFG180E0723","MP-L"),
    "Adjustable Ergonomic Electronic Standing Desk - Motiongrey - White Frame": ("9SIAFG17P44124", "MG1-White"),
    "MotionGrey-Black Desk Frame": ("9SIAFG17NX0510", "MG-Black"),
    "Adjustable Ergonomic Electronic Standing Desk - Motiongrey - Grey Frame": ("9SIAFG18GG9485", "MGFrame-Grey")
}
