# Generated by Django 2.0.5 on 2018-05-18 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chair', '0002_auto_20180518_1956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='county',
            new_name='country',
        ),
    ]
