# Generated by Django 2.0.5 on 2018-05-18 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chair', '0004_order_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
