# Generated by Django 2.0.5 on 2018-05-19 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chair', '0005_customer_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='newegg_feed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
