# Generated by Django 2.0.5 on 2018-05-21 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chair', '0008_auto_20180521_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_line_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
