# Generated by Django 2.0.5 on 2018-05-22 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chair', '0009_order_order_line_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
