# Generated by Django 2.0.5 on 2018-05-27 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chair', '0010_order_shipping_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='carrier_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
