# Generated by Django 2.0.5 on 2018-05-27 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chair', '0011_auto_20180527_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='newegg_shipped',
            field=models.BooleanField(default=False),
        ),
    ]
