# Generated by Django 2.0.5 on 2018-05-29 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chair', '0012_order_newegg_shipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bestbuy_filled',
            field=models.BooleanField(default=False),
        ),
    ]
