# Generated by Django 2.0.5 on 2018-06-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chair', '0017_order_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='part_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='product_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
