# Generated by Django 2.0.5 on 2018-05-19 23:16

from django.db import migrations


def create_autofulfill(apps, schema_editor):
    order_status = apps.get_model("chair", "OrderStatus")
    order = apps.get_model("chair", "Order")
    order_status.objects.filter(product_name__isnull=True).delete()
    products = order.objects.all().values_list('product_name', 'part_number').distinct()
    for name, part in products:
        if part:
            order_status.objects.create(auto_fulfill=False, part_number=part, product_name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('chair', '0018_auto_20180605_1419'),
    ]

    operations = [
        migrations.RunPython(create_autofulfill, reverse_code=migrations.RunPython.noop)
    ]
