# Generated by Django 2.0.5 on 2018-08-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chair', '0019_auto_20180605_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
