# Generated by Django 2.0.5 on 2018-07-31 00:40

from django.db import migrations, models


def fill_source(apps, schema_editor):
    order = apps.get_model("chair", "Order")
    order.objects.all().update(source="bestbuy")


class Migration(migrations.Migration):

    dependencies = [
        ('chair', '0019_auto_20180605_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RunPython(fill_source, reverse_code=migrations.RunPython.noop)
    ]

